### ISSUE TITLE
Me ajuda 

### ISSUE THREAD

**Issue by mtabrantes** [eduardomafra/thecrims-bot#2]
Como faço pra entrar em contato com você?, nao estou conseguindo fazer funcionar

**Comment by mtabrantes** [comment]
@eduardomafra

**Comment by luucassoares** [comment]
Eu consegui rodar aqui. Qual problema vc está tendo?

**Comment by mtabrantes** [comment]
> Eu consegui rodar aqui. Qual problema vc está tendo?
eu queria saber como faço pra rodar ele, é no antigo f12?, teria algum meio de ctt pra falar ctg? skype, discord, email ?

**Comment by luucassoares** [comment]
mano eu abro o projeto no visual studio e compilo, só isso..

dai já abre o cmd/terminal com o bot executando

**Comment by mtabrantes** [comment]
> mano eu abro o projeto no visual studio e compilo, só isso..
> 
> dai já abre o cmd/terminal com o bot executando

mano to boiando legal :/

**Comment by mtabrantes** [comment]
> > mano eu abro o projeto no visual studio e compilo, só isso..
> > dai já abre o cmd/terminal com o bot executando
> 
> mano to boiando legal :/

tem algum link pra tutorial ?

**Comment by eduardomafra** [comment]
> 
> 
> > > mano eu abro o projeto no visual studio e compilo, só isso..
> > > dai já abre o cmd/terminal com o bot executando
> > 
> > 
> > mano to boiando legal :/
> 
> tem algum link pra tutorial ?

Boa noite @mtabrantes, tudo bem?
Veja bem, o bot funciona porém ele apenas faz roubos automaticamente até os tickets acabarem, o bot foi desenvolvido para fins de aprendizado.
Se quiser rodar o bot você precisa instalar o [Visual Studio](https://visualstudio.microsoft.com/pt-br/thank-you-downloading-visual-studio/?sku=Community&rel=16), abrir o projeto pelo arquivo com extensão .csproj e executá-lo dentro do Visual Studio. A partir daí o funcionamento do bot é intuitivo.
Lembrando que o bot foi desenvolvido apenas para compartilhar conhecimento em programação, portanto pode não ser muito útil para jogadores hardcore.
