### ISSUE TITLE
Error code 0

### ISSUE THREAD

**Issue by lasteron** [eduardomafra/thecrims-bot#3]
Estava funcionando normalmente, mas agora sempre que efetuo o login o console fecha e dã o erro com o codigo 0

**Comment by lasteron** [comment]
Ajuda pf, tava salvando mt HAHAHAHA

**Comment by eduardomafra** [comment]
Bom dia @lasteron, obrigado pelo feedback!
Verifiquei que adicionaram um parâmetro a mais na requisição de roubos, já modifiquei o código e commitei.
Por favor, atualize o repositório e teste mais uma vez.

**Comment by hendrikmelo** [comment]
Estou recebendo o mesmo erro
